# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

source = ~/.config/hypr/conf/layouts/default.conf

binds {
  workspace_back_and_forth = true
}
