# Laptop-specific config (hostname: panda)
# TODO: Update monitor config for your laptop

monitor=eDP-1,preferred,auto,1

input {
    accel_profile = flat
    sensitivity = 0.4
    touchpad {
        natural_scroll = true
    }
}
