# -----------------------------------------------------
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------

input {
    kb_layout = be,us
    kb_options = grp:alt_shift_toggle
    resolve_binds_by_sym = true
    numlock_by_default = true
    touchpad {
        natural_scroll = true
    }
}

# -- Per-device keyboard layouts --
# External keyboard (Planck) always uses QWERTY
device {
    name = zsa-technology-labs-planck-ez-glow
    kb_layout = us
    kb_variant = 
}
# Laptop keyboard always uses AZERTY  
device {
    name = at-translated-set-2-keyboard
    kb_layout = be
    kb_variant =
}
