# -----------------------------------------------------
# Layouts (with gestures for laptop)
# -----------------------------------------------------

source = ~/.config/hypr/conf/layouts/default.conf

gesture = 3, horizontal, workspace

binds {
  workspace_back_and_forth = true
}
