# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# intentionally launches megasync twice so it goes to the tray
# see: https://github.com/meganz/MEGAsync/issues/161#issuecomment-797917923
exec-once = sleep 60; megasync &
exec-once = discord --start-minimized &
exec-once = slack --startup &

# fixes terrible font scaling issues for some apps
# see: https://github.com/hyprwm/Hyprland/discussions/7923#discussioncomment-10766889
xwayland {
  force_zero_scaling = true
}

general {
  border_size = 2
  gaps_in = 2
  gaps_out = 2
}

# disable opacity on all windows; it sucks
decoration {
  active_opacity = 1
  inactive_opacity = 1
  fullscreen_opacity = 1
}

# flameshot
windowrule {
  name = windowrule-1
  move = (0) (0)
  pin = on
  border_size = 0
  stay_focused = on
  float = on
  opaque = on
  match:class = (flameshot)
}

# source device-specific config (monitor, keyboard, etc)
source = ~/.config/hypr/conf/device.conf

source = ~/.config/hypr/conf/games.conf
