# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# intentionally launches megasync twice so it goes to the tray
# see: https://github.com/meganz/MEGAsync/issues/161#issuecomment-797917923
exec-once = sleep 60; megasync &
# exec-once = while ! dbus-send --session --dest=org.kde.StatusNotifierWatcher --print-reply /StatusNotifierWatcher org.freedesktop.DBus.Properties.Get string:org.kde.StatusNotifierWatcher string:IsStatusNotifierHostRegistered 2>/dev/null | grep -q true; do sleep 1; done; discord --start-minimized &
exec-once = sleep 5; discord --start-minimized &
exec-once = sleep 5; slack --startup &

# fixes terrible font scaling issues for some apps
# see: https://github.com/hyprwm/Hyprland/discussions/7923#discussioncomment-10766889
xwayland {
  force_zero_scaling = true
}

general {
  border_size = 2
  gaps_in = 2
  gaps_out = 2
  col.active_border = $inverse_primary
}

# disable opacity on all windows; it sucks
decoration {
  active_opacity = 1
  inactive_opacity = 1
  fullscreen_opacity = 1
}

# flameshot
windowrule {
  name = windowrule-flameshot
  move = (0) (0)
  pin = on
  border_size = 0
  stay_focused = on
  float = on
  opaque = on
  match:class = (flameshot)
}

# calendar top-right (overrides glass theme default of top-left)
windowrule {
  name = ml4w-calendar
  match:class = (com.ml4w.calendar)
  float = true
  move = ((monitor_w*1)-window_w-20) (76)
  pin = true
  size = 400 400
}

# jetbrains IDE popup fix
# see: https://github.com/hyprwm/Hyprland/discussions/11981
windowrule {
  name = windowrule-jetbrains-popups
  match:class = ^jetbrains-.+$
  match:float = true
  stay_focused = on
  no_initial_focus = on
  no_follow_mouse = on
}

# source device-specific config (monitor, keyboard, etc)
source = ~/.config/hypr/conf/device.conf

source = ~/.config/hypr/conf/games.conf
