# Launch steam games in fullscreen on monitor 1 and workspace 10
windowrule {
  name = windowrule-steam-games
  fullscreen = 2
  monitor = 1
  workspace = 10
  match:class = ^steam_app_\d+$
}

workspace = 10, border:false, rounding:false
