source = ~/.config/hypr/conf/keybindings/default.conf

# move Sidepad from S to P
bind = $mainMod, P, exec, ~/.config/ml4w/scripts/sidepad.sh --init                        # Init Sidepad
bind = $mainMod SHIFT, P, exec, ~/.config/ml4w/scripts/sidepad.sh --select                # Select Sidepad

# flameshot screenshot
bind = $mainMod, S, exec, QT_SCALE_FACTOR=0.8335 flameshot gui
bind = $mainMod SHIFT, S, exec, QT_SCALE_FACTOR=0.8335 flameshot gui
