# Per-device knobs, sourced by scripts/apply.sh. Only a device that differs from
# the graphical default needs a file here.
#
# aardwolf is a VPS: no display, no session, nothing to theme.

GRAPHICAL=0

# The only machine here that isn't Arch. Package names don't carry across, so
# this also picks setup/packages.apt.txt over setup/packages.txt as the base list.
PKG_MANAGER=apt

# A graphical device takes all of home/; a headless one names what it keeps,
# because almost none of that tree means anything without a session. Naming the
# keepers rather than the drops means a new config directory added to home/ has
# to be opted in here before it reaches this machine.
#
# .config/btop is deliberately absent: its only local change is color_theme =
# "matugen", and the theme it names is generated by the wallpaper pipeline that
# a headless host doesn't have.
STOW_PATHS=(
  .bashrc
  .zshrc
  .config/zshrc
  .config/ohmyposh
)
