# Per-device knobs, sourced by scripts/apply.sh. Only a device that differs from
# the graphical default needs a file here.
#
# aardwolf is a VPS: no display, no session, nothing to theme.

GRAPHICAL=0

# The only machine here that isn't Arch. Package names don't carry across, so
# this also picks setup/packages.apt.txt over setup/packages.txt as the base list.
PKG_MANAGER=apt

# A graphical device takes all of home/; a headless one names what it keeps,
# because almost none of that tree means anything without a session. Naming the
# keepers rather than the drops means a new config directory added to home/ has
# to be opted in here before it reaches this machine.
#
# Two deliberate absences:
#
# .config/btop: its only local change is color_theme = "matugen", and the theme
# it names is generated by the wallpaper pipeline that a headless host doesn't
# have.
#
# .bashrc: this is the one path where the distro's own copy is worth more than
# ours. home/.bashrc is an Arch skeleton — two colour aliases, a PS1, and a PATH
# line 00-init already sets for zsh. Ubuntu ships a fuller one, and every
# installer that has touched this box (fnm, cargo, pnpm) has appended to it, as
# has the paseo.env block. Stowing over that would trade live machine-local
# config for a worse file, and stow refuses the overwrite anyway. bash is only
# the login shell here until chsh points at zsh; the zsh side is fully stowed.
STOW_PATHS=(
  .zshrc
  .config/zshrc
  .config/ohmyposh
)
